export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const CLEAR_ERROR = 'CLEAR_ERROR';

export const LOGOUT_LOADING = 'LOGOUT_LOADING';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const CHECK_AUTH_STATE_LOADING = 'CHECK_AUTH_STATE_LOADING';
export const CHECK_AUTH_STATE_SUCCESS = 'CHECK_AUTH_STATE_SUCCESS';
export const CHECK_AUTH_STATE_ERROR = 'CHECK_AUTH_STATE_ERROR';


export const LIBROS_LOADING = 'LIBROS_LOADING';
export const LIBROS_SUCCESS = 'LIBROS_SUCCESS';
export const LIBROS_ERROR = 'LIBROS_ERROR';

export const DETALLE_LIBRO_LOADING = 'DETALLE_LIBRO_LOADING';
export const DETALLE_LIBRO_SUCCESS = 'DETALLE_LIBRO_SUCCESS';
export const DETALLE_LIBRO_ERROR = 'DETALLE_LIBRO_ERROR';


export const COMENTARIOS_LOADING = 'COMENTARIOS_LOADING';
export const COMENTARIOS_SUCCESS = 'COMENTARIOS_SUCCESS';
export const COMENTARIOS_ERROR = 'COMENTARIOS_ERROR';
export const ADD_COMENTARIO = 'ADD_COMENTARIO';
export const COMENTARIOS_VALORACION_MEDIA = 'COMENTARIOS_VALORACION_MEDIA';


export const DISCUSIONES_LOADING = 'DISCUSIONES_LOADING';
export const DISCUSIONES_SUCCESS = 'DISCUSIONES_SUCCESS';
export const DISCUSIONES_ERROR = 'DISCUSIONES_ERROR';
export const ADD_DISCUSION = 'ADD_DISCUSION';


export const ADD_TO_PENDIENTE = 'ADD_TO_PENDIENTE';
export const MOVE_TO_PENDIENTE = 'MOVE_TO_PENDIENTE';
export const ADD_TO_LEYENDO = 'ADD_TO_LEYENDO';
export const MOVE_TO_LEYENDO = 'MOVE_TO_LEYENDO';
export const ADD_TO_COMPLETADO = 'ADD_TO_COMPLETADO';
export const MOVE_TO_COMPLETADO = 'MOVE_TO_COMPLETADO';