export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_LOADING = 'LOGOUT_LOADING';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const CHECK_AUTH_STATE_LOADING = 'CHECK_AUTH_STATE_LOADING';
export const CHECK_AUTH_STATE_SUCCESS = 'CHECK_AUTH_STATE_SUCCESS';
export const CHECK_AUTH_STATE_ERROR = 'CHECK_AUTH_STATE_ERROR';


export const LIBROS_LOADING = 'LIBROS_LOADING';
export const ADD_LIBROS = 'ADD_LIBROS';
export const LIBROS_FAILED = 'LIBROS_FAILED';
export const COMENTARIOS_LOADING = 'COMENTARIOS_LOADING';
export const ADD_COMENTARIOS = 'ADD_COMENTARIOS';
export const COMENTARIOS_FAILED = 'COMENTARIOS_FAILED';
export const DISCUSIONES_LOADING = 'DISCUSIONES_LOADING';
export const ADD_DISCUSIONES = 'ADD_DISCUSIONES';
export const DISCUSIONES_FAILED = 'DISCUSIONES_FAILED';
export const EVENTOS_LOADING = 'EVENTOS_LOADING';
export const ADD_EVENTOS = 'ADD_EVENTOS';
export const EVENTOS_FAILED = 'EVENTOS_FAILED';
export const ADD_TO_PENDIENTE = 'ADD_TO_PENDIENTE';
export const MOVE_TO_PENDIENTE = 'MOVE_TO_PENDIENTE';
export const ADD_TO_LEYENDO = 'ADD_TO_LEYENDO';
export const MOVE_TO_LEYENDO = 'MOVE_TO_LEYENDO';
export const ADD_TO_COMPLETADO = 'ADD_TO_COMPLETADO';
export const MOVE_TO_COMPLETADO = 'MOVE_TO_COMPLETADO';